# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'FitMap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FitMap

  target 'FitMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FitMapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'GoogleMaps'
pod 'GooglePlaces'
end
